// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDglyjMokiTVKXTUM3uVUoDUh0s8hX1e0A',
    appId: '1:79250892296:web:1f8457006a0ba810cc13bd',
    messagingSenderId: '79250892296',
    projectId: 'my-app-90b9a',
    authDomain: 'my-app-90b9a.firebaseapp.com',
    storageBucket: 'my-app-90b9a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5UfeeXuF8rUaf3UCvkBrwvXZ_5wLKVE8',
    appId: '1:79250892296:android:4d242d2e02d0f7cacc13bd',
    messagingSenderId: '79250892296',
    projectId: 'my-app-90b9a',
    storageBucket: 'my-app-90b9a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8ib6BDdqrn0WdcCBTeshxR6nlGJPnOjk',
    appId: '1:79250892296:ios:44314f231faacb48cc13bd',
    messagingSenderId: '79250892296',
    projectId: 'my-app-90b9a',
    storageBucket: 'my-app-90b9a.appspot.com',
    iosClientId: '79250892296-4dij4d9brf4unhe59tufqnpbm0gfed55.apps.googleusercontent.com',
    iosBundleId: 'com.example.app1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8ib6BDdqrn0WdcCBTeshxR6nlGJPnOjk',
    appId: '1:79250892296:ios:44314f231faacb48cc13bd',
    messagingSenderId: '79250892296',
    projectId: 'my-app-90b9a',
    storageBucket: 'my-app-90b9a.appspot.com',
    iosClientId: '79250892296-4dij4d9brf4unhe59tufqnpbm0gfed55.apps.googleusercontent.com',
    iosBundleId: 'com.example.app1',
  );
}
